version: "2.0"
services:
  web:
    image: jhonny535/akash-cicd-demo:latest
    expose:
      - port: 80
        as: 80
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 128Mi
        storage:
          size: 256Mi
  placement:
    akash:
      attributes:
        host: akash
      pricing:
        web:
          denom: uakt
          amount: 500
deployment:
  web:
    akash:
      profile: web
      count: 1
